module.exports = [
  {
    date: "JUL 2025 — DEC 2025",
    role: "Product Engineer (Frontend)",
    company: "CUiT Indonesia",
    job: [
      "Improved dashboard UI consistency and usability by refactoring fragmented components and standardizing layouts across key modules.",
      "Resolved production frontend issues affecting core user flows, reducing UI inconsistencies and improving release stability.",
      "Refactored legacy frontend components to improve maintainability and reduce recurring UI regressions across key dashboard modules.",
      "Used AI coding tools Claude Code to support frontend development, debugging, refactoring, and implementation planning.",
    ],
    tags: ["Vue.js", "Pinia", "Tailwind CSS"],
    link: "https://cuit.id/",
  },
  {
      date: "Mar 2022 — JUL 2025",
      role: "Product Engineer II (Frontend)",
      company: "Zero One Group",
      job: [
        "Identified and resolved performance bottlenecks in large dataset rendering (10,000+ records) by implementing DOM virtualization and optimizing data fetching strategy, reducing UI freeze incidents and improving interaction responsiveness under heavy load.",
        "Resolved critical authentication issue by coordinating with backend to implement cookie revocation endpoint, fixing HTTP-only cookie logout limitation.",
        "Built real-time AI streaming feature (SSE), handling partial rendering, connection lifecycle, and ensuring UI consistency during long-running processes.",
        "Implemented real-time meeting recording and AI summary UI on the frontend, handling client-side recording, streaming data to backend APIs, and rendering incremental summaries via SSE for long-running processes.",
        "Contributed to internal design system, creating reusable UI components and patterns used across multiple client projects.",
        "Delivered across multiple stacks (React, Vue, Next.js, TypeScript) depending on project needs, including lightweight tools like HTMX and Alpine.js.",
        "Built and maintained data visualization dashboards using Recharts.js, implementing interactive charts, filters, loading/error states, and responsive layouts to help users analyze operational data more effectively.",
        "Used AI coding Claude Code support frontend development, debugging, refactoring, and implementation planning while manually reviewing and validating the output.",
      ],
    tags: [
      "React.js",
      "Next.js",
      "Htmx",
      "Tailwind CSS",
      "TypeScript",
      "Vue.js",
      "JavaScript",
      "Zustand",
      "React Query",
    ],
    link: "https://zero-one-group.com/",
    },
    {
      date: "SEP 2020 – JAN 2022",
      role: "Frontend Developer",
      company: "Pallaka Studio",
      job: [
        "Initiated frontend stack migration from Vue 2 to React after identifying TypeScript limitations, establishing a more scalable and maintainable development standard.",
        "Built and maintained production web applications using React, Vue, and modern UI libraries (Chakra UI, Vuetify).",
        "Improved development efficiency by promoting TypeScript-first practices, reducing debugging friction and runtime errors.",
        "Standardized UI patterns and component usage, ensuring consistency across multiple client projects.",
        "Delivered client-facing features end-to-end on the frontend, supporting iterative project requirements and tight delivery timelines.",
      ],
      tags: ["Vue.js", "Tailwind CSS", "React.js", "Chakra ui", "Vuex", "TypeScript", "Vuetifyjs"],
      link: "https://pallakatechno.co.id/",
    },
    {
      date: "FEB 2020 – JUL 2020",
      role: "Frontend Developer",
      company: "Magau Jaya Digital",
      job: [
        "Built core frontend features for an internal e-learning platform from early development stage, implementing UI and integrating REST APIs.",
        "Translated backend data structures into usable interfaces, ensuring accurate data flow and consistent user experience.",
        "Collaborated with backend developers to establish stable integration patterns, supporting initial platform development.",
      ],
      tags: ["Vue.JS", "Tailwind CSS", "Vuex"],
      link: "https://www.magaugroup.co.id/",
    },
];
