module.exports = [
  {
    id: "1",
    title: "chore: ignore templ.go file",
    repository: "Melkeydev/go-blueprint",
    repositoryUrl: "https://github.com/Melkeydev/go-blueprint",
    prNumber: 248,
    prUrl: "https://github.com/Melkeydev/go-blueprint/pull/248",
    status: "merged",
    mergedDate: "2024-06-10",
    description:
      "Added templ.go files to .gitignore to prevent generated template files from being committed to version control.",
    type: "chore",
    comments: 1,
  },
  {
    id: "2",
    title: "fix(types): Use ExpectTypeOf from vitest to test types",
    repository: "honojs/hono",
    repositoryUrl: "https://github.com/honojs/hono",
    prNumber: 1458,
    prUrl: "https://github.com/honojs/hono/pull/1458",
    status: "merged",
    mergedDate: "2023-09-15",
    description:
      "Improved type testing by using ExpectTypeOf from vitest instead of custom type assertions for better type safety.",
    type: "bug-fix",
    comments: 4,
  },
  {
    id: "3",
    title:
      "chore(documentation): update the documentation for installing dependencies",
    repository: "sonikjs/sonik",
    repositoryUrl: "https://github.com/sonikjs/sonik",
    prNumber: 2,
    prUrl: "https://github.com/sonikjs/sonik/pull/2",
    status: "merged",
    mergedDate: "2023-08-05",
    description:
      "Updated installation documentation to provide clearer instructions for dependency management and setup process.",
    type: "documentation",
    comments: 1,
  },
  {
    id: "4",
    title: "docs(core): add pnpm command for storybook plugin",
    repository: "nrwl/nx",
    repositoryUrl: "https://github.com/nrwl/nx",
    prNumber: 17768,
    prUrl: "https://github.com/nrwl/nx/pull/17768",
    status: "merged",
    mergedDate: "2023-06-27",
    description:
      "Added pnpm support documentation for the Storybook plugin, improving package manager compatibility.",
    type: "documentation",
    comments: 12,
  },
  {
    id: "5",
    title: "feat(zero-ui): create component tag",
    repository: "zero-one-group/zog-ui",
    repositoryUrl: "https://github.com/zero-one-group/zog-ui",
    prNumber: 168,
    prUrl: "https://github.com/zero-one-group/zog-ui/pull/168",
    status: "merged",
    mergedDate: "2023-03-20",
    description:
      "Created a new Tag component for the Zero UI design system with multiple variants and customization options.",
    type: "feature",
    comments: 1,
  },
  {
    id: "6",
    title: "feat(zero-ui): create component popconfirm",
    repository: "zero-one-group/zog-ui",
    repositoryUrl: "https://github.com/zero-one-group/zog-ui",
    prNumber: 165,
    prUrl: "https://github.com/zero-one-group/zog-ui/pull/165",
    status: "merged",
    mergedDate: "2023-03-14",
    description:
      "Implemented Popconfirm component with confirmation dialogs for user actions requiring explicit confirmation.",
    type: "feature",
    comments: 3,
  },
];
