module.exports = [
  {
    id: "1",
    title: "Ignore generated templ.go files",
    repository: "Melkeydev/go-blueprint",
    repositoryUrl: "https://github.com/Melkeydev/go-blueprint",
    prNumber: 248,
    prUrl: "https://github.com/Melkeydev/go-blueprint/pull/248",
    status: "Merged",
    mergedDate: "2024-06-10",
    description:
      "Added templ.go files to .gitignore to keep generated template files out of version control.",
    type: "Chore",
    comments: 1,
  },
  {
    id: "2",
    title: "Use ExpectTypeOf from Vitest to test types",
    repository: "honojs/hono",
    repositoryUrl: "https://github.com/honojs/hono",
    prNumber: 1458,
    prUrl: "https://github.com/honojs/hono/pull/1458",
    status: "Merged",
    mergedDate: "2023-09-15",
    description:
      "Improved type testing by replacing custom type assertions with ExpectTypeOf from Vitest.",
    type: "Bug fix",
    comments: 4,
  },
  {
    id: "3",
    title: "Update dependency installation documentation",
    repository: "sonikjs/sonik",
    repositoryUrl: "https://github.com/sonikjs/sonik",
    prNumber: 2,
    prUrl: "https://github.com/sonikjs/sonik/pull/2",
    status: "Merged",
    mergedDate: "2023-08-05",
    description:
      "Updated installation documentation with clearer dependency management and setup instructions.",
    type: "Documentation",
    comments: 1,
  },
  {
    id: "4",
    title: "Add pnpm command for Storybook plugin docs",
    repository: "nrwl/nx",
    repositoryUrl: "https://github.com/nrwl/nx",
    prNumber: 17768,
    prUrl: "https://github.com/nrwl/nx/pull/17768",
    status: "Merged",
    mergedDate: "2023-06-27",
    description:
      "Added pnpm support documentation for the Storybook plugin, improving package manager compatibility.",
    type: "Documentation",
    comments: 12,
  },
  {
    id: "5",
    title: "Create Tag component for Zero UI",
    repository: "zero-one-group/zog-ui",
    repositoryUrl: "https://github.com/zero-one-group/zog-ui",
    prNumber: 168,
    prUrl: "https://github.com/zero-one-group/zog-ui/pull/168",
    status: "Merged",
    mergedDate: "2023-03-20",
    description:
      "Created a Tag component for the Zero UI design system with multiple variants and customization options.",
    type: "Feature",
    comments: 1,
  },
  {
    id: "6",
    title: "Create Popconfirm component for Zero UI",
    repository: "zero-one-group/zog-ui",
    repositoryUrl: "https://github.com/zero-one-group/zog-ui",
    prNumber: 165,
    prUrl: "https://github.com/zero-one-group/zog-ui/pull/165",
    status: "Merged",
    mergedDate: "2023-03-14",
    description:
      "Implemented a Popconfirm component for actions that require explicit user confirmation.",
    type: "Feature",
    comments: 3,
  },
];
